# -*- coding: utf-8 -*-
"""pytorch-nn-module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9JVaahEDkzwmR0GR3OE7-khODnUgPeL
"""

# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

# show model weights
model.linear2.weight

!pip install torchinfo

from torchinfo import summary

summary(model, input_size=(10, 5))

